### ISSUE TITLE
Crash on Startup Version 6.3.0, Nutrition 4.5.0, 4.6.0 conflict

### ISSUE THREAD

**Issue by WolfBV** [Sunconure11/compitum-magia-issues#11]
Crash on startup due to both Nutrition 4.5.0 and Nutrition 4.6.0 being in the mods folder. This issue comes after deleting the pack and reinstalling it.

**Comment by WolfBV** [comment]
Continues into 6.3.1.

**Comment by Sunconure11** [comment]
This shouldn't be a thing anymore.
