### ISSUE TITLE
Consecrations's Holy possibly not applying to certain enchantments/weapons/entities

### ISSUE THREAD

**Issue by WolfBV** [Sunconure11/compitum-magia-issues#12]
![Screen Shot 2020-10-10 at 6 29 20 PM](https://user-images.githubusercontent.com/47493126/95668949-60c7b000-0b2f-11eb-805e-c08b466a1c98.png)

Taken from console while loading the pack.

CM version 6.7.11

**Comment by Sunconure11** [comment]
That is because those items do not exist in the pack. It can safely be ignored.
