### ISSUE TITLE
Received string length is longer than maximum allowed

### ISSUE THREAD

**Issue by Jwellison** [Sunconure11/compitum-magia-issues#13]
Running a server with the 1.12.2 version. Clients will receive this bug and get kicked. I'm fairly certain it is caused by a mob, I just do not know which mob. It's not a crash so there are no logs.

**Comment by Sunconure11** [comment]
https://forums.minecraftforge.net/topic/77823-solved1122-the-received-string-length-is-longer-than-maximum-allowed-29-20/
