### ISSUE TITLE
Summoned pets from electroblob's wizardry are hostile to owner.

### ISSUE THREAD

**Issue by gittycup** [Sunconure11/compitum-magia-issues#8]
Something in the mod pack is conflicting with summoned pets from electroblob's wizardry.

Skeleton Legion, spider swarm, summon phoenix, ice giant, Silverfish Swarm Master etc.
These pets are all hostile, especially at night.
I have turned off friendly fire and also attac owner damage retaliation as well to no avail.

**Comment by gittycup** [comment]
This seems to be an issue with Rough mobs 2.
Others have made the mod author aware but no news as of Oct. 23 2018.
This means electroblob's wizardry, pets bats, and other mods in the pack are highly effected until Rough mobs 2 is fixed. Unfortunately the bug in Rough mobs 2 also makes NPC from Coherent Villages hostile and again is a known issue.

**Comment by Sunconure11** [comment]
Shit, how did I miss this?

**Comment by Sunconure11** [comment]
Also, this has been fixed in dev, due to Rough Mobs having been updated.
